apiVersion: v1
kind: Service
metadata:
  name: portal-service2
spec:
  selector:
    app: uniview-spec
  ports:
    - protocol: TCP
      port: 3006
      targetPort: 3006
      nodePort: 30007
  type: NodePort
