---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.app_name }}'
  namespace: '{{ .Values.name_space }}'
  labels:
    app: uniview
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uniview
  template:
    metadata:
      labels:
        app: uniview
    spec:
      containers:
        - name: uniview-portal
          image: computingstack/univew-openstack-portal:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3006
            name: http-web
            protocol: TCP
            #imagePullSecrets:
            #- name: uniview-registry
          env:
            -	name: db_host
              value: {{ .Values.db_host }} 
            -	name: db_user
              value: {{ .Values.db_user }} 
            -	name: db_pass
              value: {{ .Values.db_pass }} 
            -	name: db_user
              value: {{ .Values.db_user }} 
              
-	

