version: '3'
services:
  collector:    
    image: computingstack/computingstack-oif-collector:2024-november    
    ports:
    - "3007:3007"
    healthcheck:
      test: curl --fail http://localhost:3007/getVersion || exit 1
      interval: 60s
      retries: 5
      #start_period: 20s
      timeout: 10s
    environment:
            #REGISTRY_AUTH: htpasswd
            #REGISTRY_AUTH_HTPASSWD_REALM: Registry
            #REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
            #REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      db_host: 192.168.1.17
      db_user: uniview
      db_password: your_password
      db_database: uniview
      rabbitmq_conn_url: amqp://intos:intos1@192.168.1.1:5672,amqp://intos:intos1@192.168.1.2:5672,amqp://intos:intos1@192.168.1.3:5672
      concurrent_sessions: 3
      region: RegionOne
      context: uniview
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        #max_attempts: 3
        window: 120s
    restart: always
