version: '3'
services:
  uniview1:
    image: computingstack/uniview-openstack-frontends:latest
    ports:
    - "3006:3006"
    healthcheck:
      test: curl --fail http://localhost:3006/getVersion || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
            #REGISTRY_AUTH: htpasswd
            #REGISTRY_AUTH_HTPASSWD_REALM: Registry
            #REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
            #REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      db_host: 192.168.2.17
      db_user: uniview
      db_password: your_pass
      db_database: uniview
      keystone_auth_url: "https://1.1.1.1 or http://1.1.1.1:5000"
      os_interface_type: admin
      os_auth_user: intos
      os_auth_pass: intos
      os_auth_project: intos
      uniview_key: xxxxx
      ceph_api_url: http://1.2.3.4:8090
      ceph_api_user: computingstack
      ceph_api_pass: your_pass
      concurrent_sessions: 6
      log_level: info
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        #max_attempts: 3
        window: 120s
    restart: always  
