version: '3'
services:
  portal1:
    image: computingstack/uniview-openstack-frontends:latest
    ports:
    - "3006:3006"
    healthcheck:
      test: curl --fail http://localhost:3006/getVersion || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    #environment:
    #  REGISTRY_AUTH: htpasswd
    #  REGISTRY_AUTH_HTPASSWD_REALM: Registry
    #  REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
    #  REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./conf:/usr/src/app/conf
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        #max_attempts: 3
        window: 120s
    restart: always
  portal2:
    image: computingstack/uniview-openstack-frontends:latest
    ports:
    - "3007:3006"
    healthcheck:
      test: curl --fail http://localhost:3006/getVersion || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      portal1:
        condition: service_healthy
    #environment:
    #  REGISTRY_AUTH: htpasswd
    #  REGISTRY_AUTH_HTPASSWD_REALM: Registry
    #  REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
    #  REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./conf:/usr/src/app/conf
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        #max_attempts: 3
        window: 120s
    restart: always
