- hosts: localhost
  #become: true
  serial: 1
  vars:
    collector_image: xxxxx.dkr.ecr.ca-central-1.amazonaws.com/computingstack-oif-collector:2025-january
    db_host: 13.23.21.153
    db_user: uniview
    db_password: password
    db_database: uniview
    concurrent_sessions: "3"
    log_level: debug
    #rabbitmq_conn_url: "amqp://openstack:my_credential@192.168.1.3:5672,amqp://openstack:my_credential@192.168.1.4:5672,amqp://openstack:my_credential@192.168.1.2:5672"
    transport_url_nova: "rabbit://user:pass@192.168.1.17:5672"
    transport_url_neutron: "rabbit://user:pass@192.168.1.17:5672"
    transport_url_cinder: "rabbit://user:pass@192.168.1.17:5672"
    region: "RegionOne"
    context: "dev"
    #listen_port: "3007"
  tasks:
    #- name: print out info
    #  debug: msg={{ groups['collector'][0]  }}


    - name: deploy uniview docker container
      docker_container:
        image: "{{ collector_image }}"
        name: uniview-collector
        state: started
        auto_remove: false
        restart: yes
        restart_policy: always
        ports:
          - "3007:{{ listen_port }}"
        network_mode: host
        env:
          db_host: "{{ db_host }}"
          db_user: "{{ db_user }}"
          db_password: "{{ db_password }}"
          db_database: "{{ db_database }}"         
          concurrent_sessions: "{{ concurrent_sessions }}"
          log_level: "{{ log_level }}"
          transport_url_nova: "{{ transport_url_nova }}"
          transport_url_neutron: "{{ transport_url_neutron }}"
          transport_url_cinder: "{{ transport_url_cinder }}"
          region: "{{ region}}"
          context: "{{ context }}"
        healthcheck:
          test: echo hello || exit 1
          interval: 90s
          retries: 5
          start_period: 20s
          timeout: 10s
